### ISSUE TITLE
numpy-1.19.4 incompatibility

### ISSUE THREAD

**Issue by rjandr** [ResearchIT/IGV-ScanFold#1]
Windows version of ScanFoldIGV (version 0.1.3) uses numpy-1.19.4 which throws this error in Windows:

 `ERROR [2020-12-01T10:18:27,733] [RuntimeUtils.java:88]  RuntimeError: The current Numpy installation ('C:\\Users\\rjand\\SCANFO~1\\scanfold\\python-3.8.6-embed-amd64\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86`

Manually replacing numpy folder with numpy-1.19.2 fixes the error.

**Comment by njbooher** [comment]
For now try this please

https://github.com/ResearchIT/scanfoldigv/releases/tag/v0.1.4

**Comment by rjandr** [comment]
The scripts run past the numpy import step now. Unfortunately it seems numpy-1.19.3 has some other issue? May need to just downgrade back to 1.19.2. *Editing to say that downgrading numpy to 1.19.2 doesn't fix the new error.

```
INFO [2020-12-01T16:27:28,712] [Main.java:205]  Startup  IGV Version user not_set
INFO [2020-12-01T16:27:28,719] [Main.java:206]  Java 11.0.9.1 (build 11.0.9.1+1) 2020-11-04
INFO [2020-12-01T16:27:28,720] [Main.java:209]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2020-12-01T16:27:28,720] [Main.java:211]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK   
INFO [2020-12-01T16:27:28,721] [Main.java:214]  Default User Directory: C:\Users\rjand\Documents
INFO [2020-12-01T16:27:28,721] [Main.java:215]  OS: Windows 10 10.0 amd64
INFO [2020-12-01T16:27:28,723] [Main.java:266]  Unknown version: user
INFO [2020-12-01T16:27:29,134] [GenomeManager.java:183]  Loading genome: C:\Users\rjand\igv\genomes\hg38.json
INFO [2020-12-01T16:27:29,582] [IGV.java:1333]  Loading 1 resources.
INFO [2020-12-01T16:27:29,585] [TrackLoader.java:123]  Loading resource, path https://s3.dualstack.us-east-1.amazonaws.com/igv.org.genomes/hg38/ncbiRefGene.txt.gz
INFO [2020-12-01T16:27:34,320] [GenomeManager.java:224]  Genome loaded.  id= hg38
INFO [2020-12-01T16:27:34,324] [CommandListener.java:120]  Listening on port 60151
INFO [2020-12-01T16:27:42,407] [HttpUtils.java:961]  Range-byte request succeeded
ERROR [2020-12-01T16:28:10,176] [RuntimeUtils.java:88]  Traceback (most recent call last):
ERROR [2020-12-01T16:28:10,192] [RuntimeUtils.java:88]    File "<string>", line 1, in <module>
ERROR [2020-12-01T16:28:10,193] [RuntimeUtils.java:88]    File "multiprocessing\spawn.py", line 116, in spawn_main
ERROR [2020-12-01T16:28:10,193] [RuntimeUtils.java:88]    File "multiprocessing\spawn.py", line 125, in _main
ERROR [2020-12-01T16:28:10,193] [RuntimeUtils.java:88]    File "multiprocessing\spawn.py", line 236, in prepare
ERROR [2020-12-01T16:28:10,193] [RuntimeUtils.java:88]    File "multiprocessing\spawn.py", line 287, in _fixup_main_from_path
ERROR [2020-12-01T16:28:10,194] [RuntimeUtils.java:88]    File "runpy.py", line 265, in run_path
ERROR [2020-12-01T16:28:10,194] [RuntimeUtils.java:88]    File "runpy.py", line 97, in _run_module_code
ERROR [2020-12-01T16:28:10,194] [RuntimeUtils.java:88]    File "runpy.py", line 87, in _run_code
ERROR [2020-12-01T16:28:10,194] [RuntimeUtils.java:88]    File "C:\Users\rjand\SCANFO~1\scanfold\ScanFold-Scan_IGV.py", line 26, in <module>
ERROR [2020-12-01T16:28:10,195] [RuntimeUtils.java:88]      import numpy as np
ERROR [2020-12-01T16:28:10,195] [RuntimeUtils.java:88]    File "C:\Users\rjand\SCANFO~1\scanfold\python-3.8.6-embed-amd64\site-packages\numpy\__init__.py", line 151, in <module>
ERROR [2020-12-01T16:28:10,195] [RuntimeUtils.java:88]      from . import random
ERROR [2020-12-01T16:28:10,195] [RuntimeUtils.java:88]    File "C:\Users\rjand\SCANFO~1\scanfold\python-3.8.6-embed-amd64\site-packages\numpy\random\__init__.py", line 179, in <module>
ERROR [2020-12-01T16:28:10,196] [RuntimeUtils.java:88]      from . import _pickle
ERROR [2020-12-01T16:28:10,196] [RuntimeUtils.java:88]    File "C:\Users\rjand\SCANFO~1\scanfold\python-3.8.6-embed-amd64\site-packages\numpy\random\_pickle.py", line 1, in <module>
ERROR [2020-12-01T16:28:10,196] [RuntimeUtils.java:88]      from .mtrand import RandomState
ERROR [2020-12-01T16:28:10,196] [RuntimeUtils.java:88]  ImportError: DLL load failed while importing mtrand: The paging file is too small for this operation to complete.
INFO [2020-12-01T16:28:10,197] [MessageUtils.java:76]  ImportError: DLL load failed while importing mtrand: The paging file is too small for this operation to complete.<br>See igv.log for more details
ERROR [2020-12-01T16:28:10,463] [RuntimeUtils.java:88]  Traceback (most recent call last):
ERROR [2020-12-01T16:28:10,463] [RuntimeUtils.java:88]    File "C:\Users\rjand\SCANFO~1\scanfold\\..\scanfold\ScanFold-Scan_IGV.py", line 285, in <module>
ERROR [2020-12-01T16:28:10,464] [RuntimeUtils.java:88]      energy_list = energies(seqlist, temperature)
ERROR [2020-12-01T16:28:10,481] [RuntimeUtils.java:88]    File "C:\Users\rjand\SCANFO~1\scanfold\ScanFoldSharedIGV.py", line 227, in energies
ERROR [2020-12-01T16:28:10,481] [RuntimeUtils.java:88]      energy_list = multiprocessing(rna_folder, [(sequence, temperature) for sequence in seq_list], 12)
ERROR [2020-12-01T16:28:10,482] [RuntimeUtils.java:88]    File "C:\Users\rjand\SCANFO~1\scanfold\ScanFoldSharedIGV.py", line 239, in multiprocessing
ERROR [2020-12-01T16:28:10,482] [RuntimeUtils.java:88]      return list(res)
ERROR [2020-12-01T16:28:10,482] [RuntimeUtils.java:88]    File "concurrent\futures\process.py", line 484, in _chain_from_iterable_of_lists
ERROR [2020-12-01T16:28:10,482] [RuntimeUtils.java:88]    File "concurrent\futures\_base.py", line 611, in result_iterator
ERROR [2020-12-01T16:28:10,482] [RuntimeUtils.java:88]    File "concurrent\futures\_base.py", line 432, in result
ERROR [2020-12-01T16:28:10,483] [RuntimeUtils.java:88]    File "concurrent\futures\_base.py", line 388, in __get_result
ERROR [2020-12-01T16:28:10,483] [RuntimeUtils.java:88]  concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
INFO [2020-12-01T16:28:11,385] [CommandExecutor.java:206]  OK
INFO [2020-12-01T16:28:11,385] [IGV.java:1333]  Loading 1 resources.
INFO [2020-12-01T16:28:11,386] [TrackLoader.java:123]  Loading resource, path C:\Users\rjand\AppData\Local\Temp\scanfold~30482\outputXXX.IGV.bp
INFO [2020-12-01T16:28:11,419] [CommandExecutor.java:206]  OK
INFO [2020-12-01T16:28:11,419] [IGV.java:1333]  Loading 1 resources.
INFO [2020-12-01T16:28:11,420] [TrackLoader.java:123]  Loading resource, path C:\Users\rjand\AppData\Local\Temp\scanfold~30482\outputXXX.final_partners_zscore.wig
INFO [2020-12-01T16:28:11,420] [CommandExecutor.java:206]  Error: C:\Users\rjand\AppData\Local\Temp\scanfold~30482\outputXXX.mfe.wig does not exist.
INFO [2020-12-01T16:28:11,421] [CommandExecutor.java:206]  Error: C:\Users\rjand\AppData\Local\Temp\scanfold~30482\outputXXX.zscore.wig does not exist.
INFO [2020-12-01T16:28:11,421] [CommandExecutor.java:206]  Error: C:\Users\rjand\AppData\Local\Temp\scanfold~30482\outputXXX.pvalue.wig does not exist.
INFO [2020-12-01T16:28:11,422] [CommandExecutor.java:206]  Error: C:\Users\rjand\AppData\Local\Temp\scanfold~30482\outputXXX.ed.wig does not exist.
INFO [2020-12-01T16:28:11,454] [CommandExecutor.java:206]  OK
INFO [2020-12-01T16:28:11,454] [IGV.java:1333]  Loading 1 resources.
INFO [2020-12-01T16:28:11,456] [TrackLoader.java:123]  Loading resource, path C:\Users\rjand\AppData\Local\Temp\scanfold~30482\outputXXX.-2filter.scanfoldvarna
```

**Comment by njbooher** [comment]
https://github.com/Spandan-Madan/Pytorch_fine_tuning_Tutorial/issues/10

I'd try:
* Reboot your computer
* Change ScanFold to use less than 12 workers for multiprocessing (maybe cap at the number of cores your machine has)

**Comment by rjandr** [comment]
Reboot wins.
